steps:
  # 1. Install dependencies
  - name: 'node:20'
    id: 'Install'
    entrypoint: 'npm'
    args: ['install']

  # 2. Build the production files
  - name: 'node:20'
    id: 'Build'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 3. Deploy to Firebase Hosting
  # Using the official Google-managed Firebase CLI image
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    id: 'Deploy'
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']

options:
  logging: CLOUD_LOGGING_ONLY
