steps:
# 1. Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # 2. Build the production files (creates the /dist folder)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 3. Deploy to Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase' # Uses the Firebase community builder
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']

options:
  logging: CLOUD_LOGGING_ONLY
